# $HOME/.config/angel/angel.conf

let mod = super
let term = "kitty"
let cursor = standard_pointer
let main_layout = angel_master_left
let rofi = "$HOME/.config/rofi/launchers/type-2/launcher.sh"
let background = "/home/angel/Backgrounds/1/angeltiled2.jpg"

set-background $background

# 2-10 use default (angel_master_right)
layouts {
    1 -> $main_layout
}

define terminal = $term
define root-cursor = $cursor
define minimized-height = 1%

set gap = 10
set border-width = 5
set fullscreen-border-width = 1
set float-move-step = 15
set default-workspace-layout = angel_simple_horizontal

color resize-border = "red";
color focused-border = "pink"
color unfocused-border = "#27DAF5"
color float-border = "green";
color fullscreen-border = "green";

declare thunar float
declare kitty tiled
declare "spectacle" float

bind-command $mod-d $rofi

bind $mod-q close-win
bind $mod-ret open-term

bind $mod-h win-down
bind $mod-t win-up
bind $mod-n win-left
bind $mod-s win-right

bind $mod-shift-h move-win-down
bind $mod-shift-t move-win-up
bind $mod-shift-n move-win-left
bind $mod-shift-s move-win-right

bind $mod-m enter-resize
bind $mod-m exit-resize

bind $mod-ctrl-h resize-down
bind $mod-ctrl-t resize-up
bind $mod-ctrl-n resize-left
bind $mod-ctrl-s resize-right

bind $mod-f toggle-fullscreen

bind $mod-space toggle-float
bind $mod-alt-space toggle-float-focus
bind $mod-b switch-float-focus

bind $mod-j minimize-win
bind $mod-tab toggle-minimize-focus

bind $mod-alt-1 tile_master_left
bind $mod-alt-2 tile_master_right
bind $mod-alt-3 tile_simple_vertical
bind $mod-alt-4 tile_simple_horizontal
bind $mod-alt-5 tile_monocle

bind $mod-1 switch-to-w1
bind $mod-2 switch-to-w2
bind $mod-3 switch-to-w3
bind $mod-4 switch-to-w4
bind $mod-5 switch-to-w5
bind $mod-6 switch-to-w6
bind $mod-7 switch-to-w7
bind $mod-8 switch-to-w8
bind $mod-9 switch-to-w9
bind $mod-0 switch-to-w10

bind $mod-shift-1 move-to-w1
bind $mod-shift-2 move-to-w2
bind $mod-shift-3 move-to-w3
bind $mod-shift-4 move-to-w4
bind $mod-shift-5 move-to-w5
bind $mod-shift-6 move-to-w6
bind $mod-shift-7 move-to-w7
bind $mod-shift-8 move-to-w8
bind $mod-shift-9 move-to-w9
bind $mod-shift-0 move-to-w10

bind $mod-shift-r restart-manager
bind $mod-shift-x quit-manager

bind $mod-shift-ctrl-u unmap-workspace
bind $mod-shift-ctrl-m map-workspace

bind $mod-shift-u unmap-window
bind $mod-shift-m map-latest-unmap
