#!/usr/bin/bash

function mov {
    cp -R $HOME/.config $HOME/linux-dotfiles/.config-clone
    cp $HOME/dev/latex/template/* $HOME/linux-dotfiles/latex
    cp -R $HOME/Backgrounds $HOME/linux-dotfiles
}; mov "${@}"

git -C ~/linux-dotfiles add . \
    && git -C ~/linux-dotfiles commit -m "changes" \
    && git -C ~/linux-dotfiles push \
    && echo "Pushed changes to github repository Successfully" \
    || echo "Failed to Push changes to github repository"
