#!/usr/bin/bash
main() {
    DIRS=("linux-dotfiles" \
        "Linux-Resources" \
        "dev" \
        "learn" \
        "niu" \
        "Pictures" \
        "leetcode" \
    )

    sudo pacman -Q > $HOME/linux-dotfiles/pac/packages

    for i in "${DIRS[@]}"; do
        sudo git -C $HOME/$i add . \
        && sudo git -C $HOME/$i commit -m "Commit" \
        && git -C $HOME/$i push \
        && echo "Successfully pushed changes to directory $i" \
        || echo "Failed to push changes to directory $i or everything is up to date"
    done
}
main
